apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: argocd
spec:
  project: default
  source:
    repoURL: repository
    path: demo/clusters
    targetRevision: HEAD
  destination: 
    name: in-cluster
    namespace: default